YOUTUBE_URL= "https://www.youtube.com/@henrymanuelquispemamani5596"
FACEBOOK_URL= "https://www.facebook.com/henrymanuel.quispemamani"
GITHUB_URL= "https://github.com/fatalbru"
HASHTAG_URL=""
HENRY_URL="https://main--qmhmblogger.netlify.app"